[build]
builder = "dockerfile"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
PYTHON_VERSION = "3.9"
PYTHONPATH = "."

[deploy.environments.production]
startCommand = "sh start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.environments.production.variables]
PYTHON_VERSION = "3.9"
PYTHONPATH = "."
NODE_ENV = "production"
